#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Pod-Markdown
Version  : 3.400
Release  : 5
URL      : https://cpan.metacpan.org/authors/id/R/RW/RWSTAUNER/Pod-Markdown-3.400.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RW/RWSTAUNER/Pod-Markdown-3.400.tar.gz
Summary  : 'Convert POD to Markdown'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Pod-Markdown-bin = %{version}-%{release}
Requires: perl-Pod-Markdown-license = %{version}-%{release}
Requires: perl-Pod-Markdown-man = %{version}-%{release}
Requires: perl-Pod-Markdown-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::Diff)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Text::Diff)
BuildRequires : perl(URI::Escape)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Pod-Markdown,
version 3.400:
Convert POD to Markdown

%package bin
Summary: bin components for the perl-Pod-Markdown package.
Group: Binaries
Requires: perl-Pod-Markdown-license = %{version}-%{release}

%description bin
bin components for the perl-Pod-Markdown package.


%package dev
Summary: dev components for the perl-Pod-Markdown package.
Group: Development
Requires: perl-Pod-Markdown-bin = %{version}-%{release}
Provides: perl-Pod-Markdown-devel = %{version}-%{release}
Requires: perl-Pod-Markdown = %{version}-%{release}

%description dev
dev components for the perl-Pod-Markdown package.


%package license
Summary: license components for the perl-Pod-Markdown package.
Group: Default

%description license
license components for the perl-Pod-Markdown package.


%package man
Summary: man components for the perl-Pod-Markdown package.
Group: Default

%description man
man components for the perl-Pod-Markdown package.


%package perl
Summary: perl components for the perl-Pod-Markdown package.
Group: Default
Requires: perl-Pod-Markdown = %{version}-%{release}

%description perl
perl components for the perl-Pod-Markdown package.


%prep
%setup -q -n Pod-Markdown-3.400
cd %{_builddir}/Pod-Markdown-3.400

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Pod-Markdown
cp %{_builddir}/Pod-Markdown-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Pod-Markdown/daef04ef846112569f1df45f15167d95214ad086 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pod2markdown

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Pod::Markdown.3
/usr/share/man/man3/Pod::Perldoc::ToMarkdown.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Pod-Markdown/daef04ef846112569f1df45f15167d95214ad086

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pod2markdown.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
